apiVersion: v1
kind: Service
metadata:
  name: canary-tomcat-svc
  labels:
    app: canary-tomcat-svc
spec:
  selector:
    type: canary-app
  type: NodePort
  ports:
  - nodePort: 31080
    port: 8080
    targetPort: 8080