apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-tomcat-deploy-v2
spec:
  selector:
    matchLabels:
      app: canary-pod-v2
  replicas: 2
  template:
    metadata:
      name: canary-pod-v2
      labels: 
        app: canary-pod-v2
        type: canary-app
    spec:
      containers:
      - name: tomcat
        image: melca/tomcat_green:8.5
        ports:
        - containerPort: 8080