apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  labels:
    app: tomcat-svc
spec:
  selector:
    app: tomcat-pod-blue
  type: NodePort
  ports:
  - nodePort: 31080
    port: 8080
    targetPort: 8080