apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-deploy
spec:
  selector:
    matchLabels:
      app: rolling-pod
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  revisionHistoryLimit: 5
  template:
    metadata:
      name: rolling-pod
      labels:
        app: rolling-pod
    spec:
      containers:
      - name: tomcat
        image: melca/tomcat_blue:8.5
        ports:
        - containerPort: 8080
